[package]
name = "sui_content_platform"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.67.1" }

[addresses]
sui_content_platform = "0x0"
